### PR TITLE
Expand TaskCreateOptions type with optional params.

### PR DESCRIPTION
**Pull request by mark-keaton**
Ran into some type errors while using task.Create, so I added the missing optional parameters.

Thanks for the great lib.

### CODE REVIEW

**Comment by darrenhillconsulting** [comment]
@mark-keaton, I don't think you got this correct.  The issue is with your implementation.  You need to cast (more correctly 'use type assertion').  

So, if you are creating a MapReduceTask ... you need to do something like this ... 

let mrTask: task.MapReduceScriptTask = <task.MapReduceScriptTask>task.create({
        taskType: task.TaskType.MAP_REDUCE
    });

Make sense?

**Comment by mark-keaton** [comment]
Hi Darren,

Even with casting, I still get TypeScript compiler errors:

image

``

**Comment by johnogle222** [comment]
Yeah this makes sense to me. I'm used to (for example) creating the task, then setting task-specific parameters like scriptId and deploymentId. I want to experiment though to see if we can make sure that only correct parameter combinations can be specified - so savedSearchId would be an invalid parameter for a MapReduceScriptTask.

I'll play around with this hopefully this evening and see if we can get a release out with this incorporated.

Thanks!

**Comment by johnogle222** [comment]
Okay I added this functionality and also made it so we won't need to explicitly cast the task type when using task.create with the task.TaskType enum.

While I was add it I removed the need to cast in some common cases for the N/format module as I ran into the need quite a bit with that one too :)

**Pull request closed without merging**
