### PR TITLE
Updated N/workbook, N/dataset, and added N/datasetLink

### PR DESCRIPTION
**Pull request by KyleJonesWinsted**
I added types for the new N/datasetLink module and also updated the N/dataset and N/workbook modules for 2021.2.

Some of the types here may disagree with the documentation in the Help Center, I've indicated each difference in the comments. In each case, my testing and the script examples in the Help Center agree with the types I've used here.

There were some existing types in N/workbook related to charts that no longer appear in Help Center documentation. I've left them untouched for now.

### CODE REVIEW

**Comment by MrRob** [comment]
I appreciate your updates here!  I was wondering though, where did you find documentation for the N/datasetLink module?

**Comment by KyleJonesWinsted** [comment]
@MrRob In the Help Center, I can see documentation with the other modules under "SuiteCloud Platform" -> "SuiteScript" -> "SuiteScript 2.x API Reference" -> "SuiteScript 2.x Modules" -> "N/datasetLink Module". If you scroll past the example code, there is a short section listing the module members.

**Comment by MrRob** [comment]
Ah yes, there it is, I think I must have been looking at a cached version of Help the other day. Thank you very much!

**Comment by MrRob** [comment]
@KyleJonesWinsted I was taking a look at your SuiteCloud unit testing stubs, very interesting stuff!  I'm curious, who are you? Are you a NetSuite partner / consultant?  I've been looking into the unit testing framework but haven't had much luck extracting much actual usefulness out of it yet :-\

**Comment by KyleJonesWinsted** [comment]
@MrRob I am a Typescript Developer with the ERP Practice at BerganKDV, we specialize in Netsuite implementations. I'm also an aspiring Rust developer, although I don't get paid to do that (yet 😁).

To be honest, I haven't gotten very much use out of unit testing for Netsuite so far. It seems to me the best use case is if I have a script that needs to do a lot of math I can verify the calculations without needing to redeploy constantly to check the results. It's also nice to be able to test specific edge cases without needing to create/modify a bunch of records each time I make a change.

**Comment by ShawnTalbert** [comment]
Easier unit tests is one thing NFT brings to the table, though I recognize
that's out-of-scope for this repo :)

That said, I still only find the occasional opportunity to do automated
unit tests for SuiteScripts.

**Pull request merged**
