### PR TITLE
Update types.d.ts and added RedirectType enum to http/https

### PR DESCRIPTION
**Pull request by darrenhillconsulting**
Upgraded mode to a String Literal Type

### CODE REVIEW

**Comment by darrenhillconsulting** [comment]
@johnogle222 Don't mean to be a pain, any chance you could accept this PR?  I hate having to modify my local versions.  Cheers!

**Comment by johnogle222** [comment]
Yeah no worries. Been a hectic couple weeks. Thanks for your patience!

**Comment by darrenhillconsulting** [comment]
@johnogle222 , outstanding!  Thanks.  Sorry if that was pushy.  See you at SuiteWorld!

**Comment by johnogle222** [comment]
Not pushy at all 👍 

I'm looking forward to it!

**Pull request merged**
