### PR TITLE
Update types.d.ts

### PR DESCRIPTION
**Pull request by darrenhillconsulting**
New updates/changes to Map/Reduce that were just released.

See Netsuite notes at https://netsuite.custhelp.com/app/answers/detail/a_id/51277

### CODE REVIEW

**Comment by JonnyBoy333** [comment]
@darrenhillconsulting I'm getting a type error on my Map/Reduce scripts now because of this Pull Request. Specifically, it is an issue with the iterator in the summaryContext. I see that `summary.output` was changed to `summary.Iterator`, which does appear to be correct looking at the suiteanswer artical you referenced. However, in practice, this does not work. In fact, if you click into the SummaryContext.Iterator method from the article you references you will see the example still uses summary.output (https://netsuite.custhelp.com/app/answers/detail/a_id/48874). I believe the documentation is in error here because summary.output.iterator() appears to be the only way this works.

**Comment by darrenhillconsulting** [comment]
My apologies.  I'm looking into it right now

**Comment by darrenhillconsulting** [comment]
@JonnyBoy333 I already have a another Pull Request in queue.  Can you make the change?

**Comment by JonnyBoy333** [comment]
I cannot, we'll have to wait for @johnogle222. You can update your pull request with the change though.

**Comment by darrenhillconsulting** [comment]
Ok, new Pull Request with fix to output.

**Comment by johnogle222** [comment]
I'm here but in a meeting. I'll get a new version up ASAP

**Comment by johnogle222** [comment]
Okay v2017.2.22 is up with this fix

**Comment by darrenhillconsulting** [comment]
Thanks @johnogle222 .  Sorry about that @JonnyBoy333

**Pull request merged**
