### PR TITLE
Add support for GL Plugins 2.x

### PR DESCRIPTION
**Pull request by jayjetley**
Now that GL Plugins are support in SuiteScript 2.x (https://suiteanswers.custhelp.com/app/answers/detail/a_id/1016989) I have added support to the typings for this.

### CODE REVIEW

**Comment by MrRob** [comment]
@jayjetley I appreciate you adding all this, I had no idea they were finally adding support for SuiteScript 2.x for this plugin!  A couple of notes on this though:
1. Can you perhaps add a comment at the top of the old SuiteGL.d.ts file noting that it is for SSV1 and where the ssv2 version is?
2. It looks like there may be some duplicate/not needed interfaces added in record.d.ts.  For example, we already have interface FindSublistLineWithValueOptions on line 69, right?

Thanks!

**Comment by jayjetley** [comment]
@MrRob Yes I was very pleased when I dicovered this, although they seem to have kept it's release quite quiet.

1. Have addded some comments for the original SuiteGL.d.ts hopefully the format works for you.
2. I've removed the duplicate interfaces and actually removed one of mine which was a duplicate of an existing interface but names slightly different.

Let me know if you need any more changes.

**Comment by MrRob** [comment]
@jayjetley I appreciate that.  In record.d.ts, could "ReadOnlyTransactionRecord" be simplified to just "ReadOnlyRecord"?  Or does anything about it make it specific to transactions?

**Comment by jayjetley** [comment]
@MrRob the name came from the Netsuite Documentation am happy to change it if you would prefer ReadOnlyRecord.

**Comment by MrRob** [comment]
@jayjetley Ah yes I see what you mean now.  In that case, what do you think about putting the ReadOnlyTransaction directly in with the glPlugin.d.ts file?  In other words, it isn't really an update to the N/record module, but is something specifically just part of the GL plugin.

**Comment by jayjetley** [comment]
@MrRob Have moved to the glPlugin.d.ts file I have also added help text to all the properties. With the FindSublistLineWithValueOptions I have duplicated this in the glPlugin.d.ts as the original isn't exported and it also allows for any differences that might appear in the future.

**Pull request merged**
