### PR TITLE
Update redirect.d.ts

### PR DESCRIPTION
**Pull request by Extend-Apps**
id is optional

### CODE REVIEW

**Comment by MrRob** [comment]
@Extend-Apps I think we've looked at this one before.  According to the documentation, id is required, right?  The way I normally redirect to a new record is just to set id to null.  What are your thoughts?

**Comment by Extend-Apps** [comment]
I have a solution in production for a while that works great when id is absent, so we know it works.  

I know there are other redirects in his library that work the same way.

I'm easy.  I'm like you and want things to line up with the documentation.

**Comment by ShawnTalbert** [comment]
Documentation first, but _reality_ should weigh in because we know the NS docs are far from perfect.

Gut feel for me is to set id to null seems clearer reading than just leaving it out (undefined).

**Comment by MrRob** [comment]
@ShawnTalbert That's a good call.  @Extend-Apps can you update the PR to keep it required but add null as an allowed value?

**Pull request closed without merging**
