### PR TITLE
Add MapReduce Example to README

### PR DESCRIPTION
**Pull request by mark-keaton**
Hi,

When I didn't see an example in your readme, I came up with this structure.

I'm not saying it's perfect, but it's what I've been using.

Thanks,
Mark

### CODE REVIEW

**Comment by darrenhillconsulting** [comment]
I felt the same thing

**Comment by cancerberoSgx** [comment]
I think we should put examples in a separate document and link it from readme - and put just a very basic one in readme and only focus on important things like entrypoint and tsconfig.

**Comment by mark-keaton** [comment]
I think that's fair.

I just live in Angular-land so much that I jump to classes from the word go. 😄 

I do like the idea of an examples page, though, like @cancerberoSgx said. Perhaps in the Wiki?

**Comment by cancerberoSgx** [comment]
@mark-keaton - your code and classes are fine! I also did a PL with examples and put them in the readme because I felt more examples were needed. But I think readme should be very concise - and BTW if this project groow it will end up having lots !

**Comment by johnogle222** [comment]
Yeah I would tend to agree the class structure here wouldn't be a recommended "first" example, and I'm honestly having a hard time seeing what the classes gain you in this context. If you wanted to take those out we could add them to the readme or if someone wants to start a wiki I'd be stoked :)

**Comment by darrenhillconsulting** [comment]
If someone sets up the wiki (i.e. create the structure and proper linkage
back to this project), I'd be happy to contribute on-going




*Darren Hill*
*Owner*
*Darren Hill Consulting Inc.*
16 Faludon Dr
Georgetown, ON  L7G1H7
Office: 416.856.6220
www.darrenhillconsulting.ca

**Comment by cancerberoSgx** [comment]
It can be done just in an "examples" folder with markdown files and an README.md so they are shown pretty in github - then just a link to this folder in the main README.md

**Pull request closed without merging**
