### PR TITLE
Proposal Core Plugin support

### PR DESCRIPTION
**Pull request by felipechang**
Hi,

This is a proposed design for enabling core plugin support, if approved others can be worked under the same format.

Below it's how it will look like, showing adaptation of the Financial Connectivity plugin example from the NetSuite help page:
```
import {EntryPoints} from "N/types";

/** getConfigurationIFrameUrl event handler */
export let getConfigurationIFrameUrl: EntryPoints.Plugins.FiConnectivity.getConfigurationIFrameUrl = (context: EntryPoints.Plugins.FiConnectivity.getConfigurationIFrameUrlContext) => {

    const configurationId = context.pluginConfiguration.getConfigurationFieldValue({fieldName: "configuration_id"});
    context.configurationIFrameUrl = "/app/site/hosting/scriptlet.nl?script=1&deploy=1&configurationId=" + configurationId;
};

/** getAccounts event handler */
export let getAccounts: EntryPoints.Plugins.FiConnectivity.getAccounts = (context: EntryPoints.Plugins.FiConnectivity.getAccountsContext) => {
    const configurationId = context.pluginConfiguration.getConfigurationFieldValue({fieldName: "configuration_id"});
    context.addAccount({
        accountMappingKey: "12345",
        displayName: "Checking (XXXX11)",
        accountType: "BANK",
        currency: "USD",
        groupName: "Bank of America",
        lastUpdated: "2020-06-30T01:23:45"
    });
};

/** getTransactionData event handler */
export let getTransactionData: EntryPoints.Plugins.FiConnectivity.getTransactionData = (context: EntryPoints.Plugins.FiConnectivity.getTransactionDataContext) => {
    const configurationId = context.pluginConfiguration.getConfigurationFieldValue({fieldName: "configuration_id"});
    const accountRequests = JSON.parse(context.accountRequestsJSON) as EntryPoints.Plugins.FiConnectivity.IAccountRequest[];
    if (accountRequests != null) {
        accountRequests.forEach(function (accountRequest) {
            const accountId = accountRequest.accountMappingKey;
            const fromDateTime = accountRequest.dataStartTime;
            const toDateTime = accountRequest.dataEndTime;

            const downloadedData = "... Retrieve the account data using a web service request or a file transfer...";

            context.addDataChunk({dataChunk: downloadedData});
        });
    }
    context.returnAccountRequestsJSON({accountsJson: context.accountRequestsJSON});
};

```

### CODE REVIEW

**Comment by MrRob** [comment]
@felipechang I love the idea of this.  I was actually just testing implementing the CustomGLPlugin script type in SSV2.  But I couldn't quite get it to work, I keep getting an error: missing ; before statement (INVOCATION_WRAPPER#23)

I could have something incorrect, but it seems to me like these plugins aren't quite supported yet even in 2020.2.  Did you have any luck actually testing what you've submitted here?

Thank you!

**Comment by felipechang** [comment]
@MrRob I'm still in the process of testing a financial connectivity and financial parser plugins for a customer, though so far everything seems to be OK:  The files have been created, uploaded, implemented (Customization > Plug-Ins >Plug -In Implementations), and added the Financial Institution + Configuration. Sandbox version is 2020.2.

As for CustomGLPlugin, we don't have it enabled on my account but I can take a look if you send it through.

**Comment by MrRob** [comment]
@felipechang Sorry, to clarify my question, have you been able to fully test this type of plugin in SSV2?  Does the NetSuite Help documentation say its supported at this point, or does it still say only SuiteScript 1.0?

**Comment by felipechang** [comment]
SS2.0 applies to three (Bank Conectivity, Financial Institution Conectivity, and Financial Institution Parser) ofr the five types of core plugins available. Only one missing would be Bank Conectivity, the rest we'll have to wait until NetSuite catches up.

image

**Pull request merged**
