### PR TITLE
Added asMappedResults and asMap methods to query.d.ts

### PR DESCRIPTION
**Pull request by sebous**

### CODE REVIEW

**Comment by MrRob** [comment]
@sebous Thank you for adding this in!  I'm closing this request, as I had also just committed an update with the asMap function.

**Comment by sebous** [comment]
ResultSet.asMappedResults method is still missing though.

**Comment by MrRob** [comment]
@sebous Ah, do you mind doing a new pull request then? I haven't modified the query module anymore so there won't be any more conflicts.  Working on the piremoval module now!

**Comment by sebous** [comment]
@MrRob done

**Pull request closed without merging**
