### PR TITLE
fix query RunSuiteQL description

### PR DESCRIPTION
**Pull request by GabrielGorta**

### CODE REVIEW

**Comment by ShawnTalbert** [comment]
The code reformatting differences in this file suggest there should probably be a standard style applied to this repo, no?

I recommend [standardjs](https://standardjs.com/) personally.

**Comment by GabrielGorta** [comment]
oh, I have prettier installed as global formater.

**Comment by MrRob** [comment]
@ShawnTalbert Probably not a bad idea!  I haven't ever used that before, I generally just do free-hand formatting.  Do you know how to set that up here?

**Comment by GabrielGorta** [comment]
btw. Github has `hide white space changes` feature.

**Comment by ShawnTalbert** [comment]
standardjs comes with a utility to check compliance. I haven't used githubs newish automation tooling but maybe it's something we could do with 'actions' or a commit hook or something.

**Pull request merged**
